### ISSUE TITLE
FreeBSD ports

### ISSUE THREAD

**Issue by army1349** [mwolf-rw/freebsd-keycloak#1]
Thanks for this!
Would you consider adding this to FreeBSD ports?

**Comment by mwolf-rw** [comment]
Yes, that's the plan. I wanted to check in with dvl@ (as he's mentioned in https://wiki.freebsd.org/WantedPorts for Keycloak) beforehand, though.

**Comment by army1349** [comment]
Perfect.
Let me know, If I can help with testing or anything.
So far I had only issue with access to keycloak folder when running under non-root user.

**Comment by ktk** [comment]
Same here, happy to test

**Comment by mwolf-rw** [comment]
Submitted to the ports bug tracker as https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252831

**Comment by mwolf-rw** [comment]
A commit references this bug:

Author: vanilla
Date: Thu Jan 21 02:21:35 UTC 2021
New revision: 562167
URL: https://svnweb.freebsd.org/changeset/ports/562167
